/* This file is generated by rust/crates/business-protocol. Do not edit. */
export const BUSINESS_PROTOCOL_VERSION = 1 as const;
export const BUSINESS_REQUEST_METHODS = [
  'initialize', 'business/status/read', 'business/shutdown', 'business-profile/list', 'skill/list',
  'tool/catalog/list', 'tool/call', 'artifact/contract/list', 'provider/capability/list', 'service/list',
  'project/create', 'project/list', 'project/read', 'project/context/read', 'brief/update', 'conversation/bind',
  'conversation/binding/read', 'plan/list', 'plan/read', 'approval/decide', 'resource/list',
] as const;
export type ProfileExecutionState = 'preparing' | 'available' | 'blocked';
export type ResourceState = 'ready' | 'missing' | 'updating' | 'blocked';
export type CapabilityAvailability = 'available' | 'degraded' | 'unavailable' | 'deprecated';
export type ServiceKind = 'local' | 'remote';
export type ProjectState = 'draft' | 'active' | 'archived';
export type BriefCompleteness = 'incomplete' | 'workable' | 'conflicting';
export type PlanState = 'draft' | 'needs_input' | 'ready_for_review' | 'approved' | 'executing' | 'delivered' | 'failed' | 'superseded' | 'canceled';
export type ApprovalDecision = 'approve' | 'request_changes';
export interface BusinessProfile { profileId: string; nameKey: string; descriptionKey: string; executionState: ProfileExecutionState; }
export interface BusinessProfileListResult { profiles: BusinessProfile[]; }
export interface SkillDescriptor { skillId: string; profileId: string; nameKey: string; descriptionKey: string; instructionPath: string; }
export interface SkillListResult { catalogVersion: number; skills: SkillDescriptor[]; }
export interface ArtifactContractDescriptor { artifactType: string; schemaVersion: number; nameKey: string; }
export interface ArtifactContractListResult { catalogVersion: number; contracts: ArtifactContractDescriptor[]; }
export interface CapabilityDescriptor { capabilityId: string; nameKey: string; inputModalities: string[]; outputModalities: string[]; availability: CapabilityAvailability; reasonKey: string; }
export interface CapabilityListResult { catalogVersion: number; capabilities: CapabilityDescriptor[]; }
export interface ServiceDescriptor { serviceId: string; nameKey: string; kind: ServiceKind; state: ResourceState; reasonKey: string; capabilityIds: string[]; }
export interface ServiceListResult { catalogVersion: number; services: ServiceDescriptor[]; }
export interface ManagedResourceDescriptor { resourceId: string; kind: 'node_runtime' | 'media_runtime'; required: boolean; platformKey: string; version: string | null; state: ResourceState; detailCode: string; executableNames: string[]; }
export interface ManagedResourceListResult { manifestVersion: number; resources: ManagedResourceDescriptor[]; }
export interface BriefInput { subject: string; audience: string; platform: string; targetDurationSeconds: number | null; aspectRatio: string; language: string; style: string; mustInclude: string[]; prohibited: string[]; deliveryFormat: string; }
export interface ProjectSummary { projectId: string; name: string; profileId: string; state: ProjectState; workspaceName: string; createdAtEpochMs: number; updatedAtEpochMs: number; }
export interface BriefRecord { briefId: string; projectId: string; version: number; completeness: BriefCompleteness; missingFields: string[]; conflicts: string[]; content: BriefInput; createdAtEpochMs: number; }
export interface ProjectCreateParams { name: string; profileId: string; workspacePath: string; brief: BriefInput; }
export interface ProjectCreateResult { project: ProjectSummary; brief: BriefRecord; }
export interface ProjectListParams { state: ProjectState | null; }
export interface ProjectListResult { projects: ProjectSummary[]; }
export interface ProjectReadParams { projectId: string; }
export interface ProjectReadResult { project: ProjectSummary; brief: BriefRecord; }
export interface ProjectContextReadParams { projectId: string; }
export interface ProjectContextReadResult { projectId: string; workspacePath: string; }
export interface BriefUpdateParams { projectId: string; expectedVersion: number; brief: BriefInput; }
export interface BriefUpdateResult { brief: BriefRecord; }
export interface ConversationBinding { projectId: string; conversationId: string; codexThreadId: string; updatedAtEpochMs: number; }
export interface ConversationBindParams { projectId: string; conversationId: string; codexThreadId: string; expectedCodexThreadId: string | null; }
export interface ConversationBindResult { binding: ConversationBinding; }
export interface ConversationBindingReadParams { projectId: string; conversationId: string; }
export interface ConversationBindingReadResult { binding: ConversationBinding; }
export interface PlanOperationInput { operationId: string; kind: string; title: string; capabilityId: string | null; dependsOn: string[]; }
export interface PlanInput { title: string; summary: string; deliverables: string[]; operations: PlanOperationInput[]; gaps: string[]; risks: string[]; }
export interface ProductionPlan { planId: string; projectId: string; version: number; state: PlanState; briefId: string; briefVersion: number; content: PlanInput; createdBy: string; approvedBy: string | null; createdAtEpochMs: number; approvedAtEpochMs: number | null; }
export interface PlanCreateParams { projectId: string; plan: PlanInput; }
export interface PlanCreateResult { plan: ProductionPlan; }
export interface PlanListParams { projectId: string; }
export interface PlanListResult { plans: ProductionPlan[]; }
export interface PlanReadParams { projectId: string; planId: string; }
export interface PlanReadResult { plan: ProductionPlan; }
export interface ApprovalReceipt { approvalId: string; projectId: string; planId: string; planVersion: number; decision: ApprovalDecision; actor: string; note: string; decidedAtEpochMs: number; }
export interface ApprovalDecideParams { projectId: string; planId: string; expectedVersion: number; decision: ApprovalDecision; note: string; }
export interface ApprovalDecideResult { plan: ProductionPlan; receipt: ApprovalReceipt; }
export interface ToolDescriptor { name: string; description: string; inputSchema: Record<string, unknown>; }
export interface ToolCatalogListResult { tools: ToolDescriptor[]; }
export interface ToolCallContext { projectId: string; conversationId: string; threadId: string; turnId: string; callId: string; }
export interface ToolCallParams { context: ToolCallContext; tool: string; arguments: Record<string, unknown>; }
export interface ToolContentItem { type: 'inputText'; text: string; }
export interface ToolCallResult { success: boolean; contentItems: ToolContentItem[]; }
export interface BusinessStatusResult { status: string; serverPid: number; protocolVersion: number; startedAtEpochMs: number; }
export interface BusinessRequestMap {
  'business/status/read': { params: Record<string, never>; result: BusinessStatusResult };
  'business/shutdown': { params: Record<string, never>; result: { accepted: boolean } };
  'business-profile/list': { params: Record<string, never>; result: BusinessProfileListResult };
  'skill/list': { params: Record<string, never>; result: SkillListResult };
  'tool/catalog/list': { params: Record<string, never>; result: ToolCatalogListResult };
  'tool/call': { params: ToolCallParams; result: ToolCallResult };
  'artifact/contract/list': { params: Record<string, never>; result: ArtifactContractListResult };
  'provider/capability/list': { params: Record<string, never>; result: CapabilityListResult };
  'service/list': { params: Record<string, never>; result: ServiceListResult };
  'resource/list': { params: Record<string, never>; result: ManagedResourceListResult };
  'project/create': { params: ProjectCreateParams; result: ProjectCreateResult };
  'project/list': { params: ProjectListParams; result: ProjectListResult };
  'project/read': { params: ProjectReadParams; result: ProjectReadResult };
  'project/context/read': { params: ProjectContextReadParams; result: ProjectContextReadResult };
  'brief/update': { params: BriefUpdateParams; result: BriefUpdateResult };
  'conversation/bind': { params: ConversationBindParams; result: ConversationBindResult };
  'conversation/binding/read': { params: ConversationBindingReadParams; result: ConversationBindingReadResult };
  'plan/list': { params: PlanListParams; result: PlanListResult };
  'plan/read': { params: PlanReadParams; result: PlanReadResult };
  'approval/decide': { params: ApprovalDecideParams; result: ApprovalDecideResult };
}
export type BusinessRequestMethod = keyof BusinessRequestMap;
export type BusinessRequestParams<M extends BusinessRequestMethod> = BusinessRequestMap[M]['params'];
export type BusinessRequestResult<M extends BusinessRequestMethod> = BusinessRequestMap[M]['result'];
